
platform :ios, '8.0'
use_frameworks!

target 'ConsoleDemo' do

    # For regular projects
    #pod 'LumberjackConsole'

    # Optional for dynamic logging
    #pod 'NBULog'

    # For development
    pod 'LumberjackConsole', :path => '../'

end
