
platform :ios, '5.0'
source 'https://github.com/CocoaPods/Specs.git'

# For regular projects
pod 'CocoaLumberjack'
#pod 'LumberjackConsole', :configurations => ['Debug']

# Optional for dynamic logging
#pod 'NBULog'

# For development
pod 'LumberjackConsole', :path => '../'
